### ISSUE TITLE
Why You have mentioned that the repos won't count towards hacktoberfest i have worked soo hard and made the projects that i have added and i have created 3 pull requests although they were merged but now on digitalOcean it shows no PR's Why did You remove that topic  : (  make it Hacktoberbest related again 

### ISSUE THREAD

**Issue by Lakhankumawat** [bajajvinamr/HacktoberFest2020#640]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mu-C00L** [comment]
I think this is done by the hacktoberfest team and not by the maintainer, as my PR was merged and it has the hacktoberfest-accepted label too but in my digital ocean profile, it has been marked invalid. 😥

**Comment by Lakhankumawat** [comment]
O okay . if you know any open source contribution which works with PR's and won't be closed like this then please like to mention

**Comment by Lakhankumawat** [comment]
As i have acknowledged that it was closed by hacktoberfest team and not the maintainer i close this issue
